### ISSUE TITLE
Error From the back end, replies not coming from server 

### ISSUE THREAD

**Issue by Funshyaj** [deralph/pi-neobot#2]
**First of all pull my edits and go through my commits to update yourself**

**Main issue below**

**Issue 1**
After running the app locally, the save error persisted and in the console it showed some thing like local host with port 5000... although everything has been changed I don't know where port 5000 is coming from again even after changing it.
**Possible causes**
- Maybe from the database
- Maybe the build folder was old(I've built a new one tho)
- maybe there's a file somewhere that needs editing
- The logic for errors in the chat page might be too cranky because of the else statement.

**Comment by deralph** [comment]
The cause of the was in the chat page in the client folder
The backendURL wasn't changed from http://localhost:5000

**Comment by Funshyaj** [comment]
> The cause of the was in the chat page in the client folder
> The backendURL wasn't changed from http://localhost:5000

Excellent..I guess I over looked that..does it work now

**Comment by deralph** [comment]
It should work now
rebuild it and push to cpanel

**Comment by Funshyaj** [comment]
Ok no problem 
Will change it to 9001 to test locally and then change it back to neobot.online For live deployment

I will close this issue when its working fine 

I will also work on the payment as well and other minor things
As well as the dark mode

**Comment by Funshyaj** [comment]
### App still not working locally or online

So after testing it locally it doesnt still work but the error message changed and this is the error message 
_**POST http://localhost:9001/generate-output 502 (Bad Gateway)**_
I have tested it online as well it stll isnt working as well
kindly make it work both locally and and online.
**kindly do these before afternoon tomorow so we can focus on other things**

**Comment by deralph** [comment]
It won't work locally if some lines of codes are not commented out and that is what is causing the error 
The error message you are getting is coming from the backend which means the backend is  responding
The code was changed from 500 to 502 as you requested that is the 502 code you are getting back
if you check the response you will recieve a message like this ```error: "an error occured, try again later",```

you can comment out the lines and check it again for any error if none kindly uncomment it back and push

**Comment by deralph** [comment]
Another thing to note is that after commenting those code you will need to change your backend url from https://neobot.online to http://localhost:9001 or else you will encounter a cors error
![bandicam 2023-03-02 06-23-18-608](https://user-images.githubusercontent.com/95740593/222455931-87f02d5e-363d-472e-8ab7-5310715b71e5.jpg) here is an image of it working well locally after all these has been put in place

**Comment by Funshyaj** [comment]
Ok great

It works locally here too but online it's still having issues why??

**Comment by Funshyaj** [comment]
The replies are coming in good well done
